### ISSUE TITLE
wdio Setup Crash at 'creating configuration file...' 

### ISSUE THREAD

**Issue by phil-lgr** [ziolko/wdio#9]
Windows 10, Node v8.9.4

Looks like the webdriverio dir does not have a build folder:

![image](https://user-images.githubusercontent.com/9644867/35924959-74f648d2-0bf2-11e8-9548-a088a4f632ae.png)

```
Packages installed successfully, creating configuration file...
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\pleger\Code\ui-starter\node_modules\webdriverio\build\lib\helpers\wdio.conf.ejs'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at renderConfigurationFile (C:\Users\pleger\Code\ui-starter\node_modules\webdriverio\build\lib\cli.js:304:28)
    at C:\Users\pleger\Code\ui-starter\node_modules\webdriverio\build\lib\cli.js:294:17
    at C:\Users\pleger\Code\ui-starter\node_modules\npm-install-package\index.js:31:5
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
The batch file cannot be found.
```

**Comment by phil-lgr** [comment]
Nevermind, retried with npm instead of yarn and it worked right away 👍 

```
Installing wdio packages:

Packages installed successfully, creating configuration file...

Configuration file was created successfully!
To run your tests, execute:

$ wdio wdio.conf.js
```

Thanks :)
